# Denotes the block length for every format
format_length = {"M":2052, "K":2745, "C":2953, "8B":512,
                "8G":8199, "9B":576, "9G":8199}

data_formats = {
    "ETL1":{
        "File format":"M",
        "class":"hand-written",
        "contents":["numeral", "roman", "special", "katakana"],
        "number of samples":141319
    },
    "ETL2":{
        "File format":"K",
        "class":"machine-printed",
        "contents":["kanji", "hiragana", "katakana", "alphanum", "special"],
        "number of samples":52796
    },
    "ETL3":{
        "File format":"C",
        "class":"hand-printed",
        "contents":["numeral", "roman", "special"],
        "number of samples":9600
    },
    "ETL4":{
        "File format":"C",
        "class":"hand-written",
        "contents":["hiragana"],
        "number of samples":6120
    },
    "ETL5":{
        "File format":"C",
        "class":"hand-printed",
        "contents":["katakana"],
        "number of samples":10608
    },
    "ETL6":{
        "File format":"M",
        "class":"hand-printed",
        "contents":["katakana", "numeral", "roman", "special"],
        "number of samples":157662
    },
    "ETL7":{
        "File format":"M",
        "class":"hand-printed",
        "contents":["hiragana"],
        "number of samples":16800
    },
    "ETL8B":{
        "File format":"8B",
        "class":"hand-printed",
        "contents":["kanji", "hiragana"],
        "number of samples":152960
    },
    "ETL8G":{
        "File format":"8G",
        "class":"hand-printed",
        "contents":["kanji", "hiragana"],
        "number of samples":152960
    },
    "ETL9B":{
        "File format":"9B",
        "class":"hand-printed",
        "contents":["kanji", "hiragana"],
        "number of samples":607200
    },
    "ETL9G":{
        "File format":"9G",
        "class":"hand-printed",
        "contents":["kanji", "hiragana"],
        "number of samples":607200
    }
}

# Shows all fields for each format, taken from
# http://etlcdb.db.aist.go.jp/etlcdb/etln/
format_fields = {
                "M":{
                    "data_number":{
                        "start":0,
                        "length":2,
                        "type":"int"
                        },
                    "character":{
                        "start":2,
                        "length":2,
                        "type":"str"
                        },
                    "sheet":{
                        "start":4,
                        "length":2,
                        "type":"int"
                        },
                    "jis":{
                        "start":6,
                        "length":1,
                        "type":"int"
                        },
                    "ebcdic":{
                        "start":7,
                        "length":1,
                        "type":"int"
                        },
                    "eval_img":{
                        "start":8,
                        "length":1,
                        "type":"int"
                        },
                    "eval_group":{
                        "start":9,
                        "length":2,
                        "type":"int"
                        },
                    "gender":{
                        "start":10,
                        "length":1,
                        "type":"int"
                        },
                    "age":{
                        "start":11,
                        "length":1,
                        "type":"int"
                        },
                    "serial":{
                        "start":12,
                        "length":4,
                        "type":"int"
                        },
                    "ind":{
                        "start":16,
                        "length":2,
                        "type":"int"
                        },
                    "occ":{
                        "start":18,
                        "length":2,
                        "type":"int"
                        },
                    "sheet_date":{
                        "start":20,
                        "length":2,
                        "type":"int"
                        },
                    "scan_date":{
                        "start":22,
                        "length":2,
                        "type":"int"
                        },
                    "sample_y":{
                        "start":24,
                        "length":1,
                        "type":"int"
                        },
                    "sample_x":{
                        "start":25,
                        "length":1,
                        "type":"int"
                        },
                    "min_lvl":{
                        "start":26,
                        "length":1,
                        "type":"int"
                        },
                    "max_lvl":{
                        "start":27,
                        "length":1,
                        "type":"int"
                        },
                    "img":{
                        "start":32,
                        "length":2016,
                        "dim":(63,64),
                        "type":"int",
                        "bitperpixel":4,
                        "n_pixels":4032
                        }
                    },
                "K":{
                    "data_number":{
                        "start":0,
                        "length":6,
                        "type":"int"
                        },
                    "mark_style":{
                        "start":6,
                        "length":1,
                        "type":"T56Code"
                        },
                    "content":{
                        "start":12,
                        "length":6,
                        "type":"T56Code"
                        },
                    "style":{
                        "start":18,
                        "length":6,
                        "type":"T56Code"
                        },
                    "CO-59_code":{
                        "start":28,
                        "length":2,
                        "type":"bin"
                        },
                    "img":{
                        "start":60,
                        "length":3600,
                        "dim":(60,60),
                        "type":"int",
                        "bitperpixel":6,
                        "n_pixels": 3600
                        }
                    },
                "C":{
                    "data_number":{
                        "start":0,
                        "length":6,
                        "type":"int"
                        },
                    "sheet":{
                        "start":6,
                        "length":6,
                        "type":"str"
                        },
                    "jis":{
                        "start":12,
                        "length":6,
                        "type":"int"
                        },
                    "ebcdic":{
                        "start":18,
                        "length":6,
                        "type":"int"
                        },
                    "character":{
                        "start":24,
                        "length":4,
                        "type":"T56Code"
                        },
                    "eval_img":{
                        "start":30,
                        "length":6,
                        "type":"int"
                        },
                    "eval_group":{
                        "start":36,
                        "length":6,
                        "type":"int"
                        },
                    "sample_y":{
                        "start":42,
                        "length":6,
                        "type":"int"
                        },
                    "sample_x":{
                        "start":48,
                        "length":6,
                        "type":"int"
                        },
                    "gender":{
                        "start":54,
                        "length":1,
                        "type":"int"
                        },
                    "age":{
                        "start":62,
                        "length":6,
                        "type":"int"
                        },
                    "ind":{
                        "start":72,
                        "length":6,
                        "type":"int"
                        },
                    "occ":{
                        "start":78,
                        "length":6,
                        "type":"int"
                        },
                    "sheet_date":{
                        "start":84,
                        "length":6,
                        "type":"int"
                        },
                    "scan_date":{
                        "start":90,
                        "length":6,
                        "type":"int"
                        },
                    "num_x":{
                        "start":96,
                        "length":6,
                        "type":"int"
                        },
                    "num_y":{
                        "start":102,
                        "length":6,
                        "type":"int"
                        },
                    "num_lvls":{
                        "start":108,
                        "length":6,
                        "type":"int"
                        },
                    "magnification":{
                        "start":114,
                        "length":6,
                        "type":"int"
                        },
                    "data_number_old":{
                        "start":120,
                        "length":6,
                        "type":"int"
                        },
                    "img":{
                        "start":288,
                        "length":3648,
                        "dim":(72,76),
                        "type":"int",
                        "bitperpixel":4,
                        "n_pixels":5472
                        }
                    },
                "8B":{
                    "sheet":{
                        "start":0,
                        "length":2,
                        "type":"int"
                        },
                    "kanji_code":{
                        "start":2,
                        "length":2,
                        "type":"bin"
                        },
                    "reading":{
                        "start":4,
                        "length":4,
                        "type":"str"
                        },
                    "img":{
                        "start":8,
                        "length":504,
                        "dim":(64,63),
                        "type":"int",
                        "bitperpixel":1,
                        "n_pixels": 4032
                        }
                    },
                "8G":{
                    "sheet":{
                        "start":0,
                        "length":2,
                        "type":"int"
                        },
                    "kanji_code":{
                        "start":2,
                        "length":2,
                        "type":"bin"
                        },
                    "reading":{
                        "start":4,
                        "length":8,
                        "type":"str"
                        },
                    "data_number":{
                        "start":12,
                        "length":4,
                        "type":"int"
                        },
                    "eval_img":{
                        "start":16,
                        "length":1,
                        "type":"int"
                        },
                    "eval_group":{
                        "start":17,
                        "length":1,
                        "type":"int"
                        },
                    "gender":{
                        "start":18,
                        "length":1,
                        "type":"int"
                        },
                    "age":{
                        "start":19,
                        "length":1,
                        "type":"int"
                        },
                    "ind":{
                        "start":20,
                        "length":2,
                        "type":"int"
                        },
                    "occ":{
                        "start":22,
                        "length":2,
                        "type":"int"
                        },
                    "sheet_date":{
                        "start":24,
                        "length":2,
                        "type":"int"
                        },
                    "scan_date":{
                        "start":26,
                        "length":2,
                        "type":"int"
                        },
                    "sample_y":{
                        "start":28,
                        "length":1,
                        "type":"int"
                        },
                    "sample_x":{
                        "start":29,
                        "length":1,
                        "type":"int"
                        },
                    "img":{
                        "start":60,
                        "length":8128,
                        "dim":(128,127),
                        "type":"int",
                        "bitperpixel":4,
                        "n_pixels": 16256
                        }
                    },
                "9B":{
                    "sheet":{
                        "start":0,
                        "length":2,
                        "type":"int"
                        },
                    "jis_kanji_code":{
                        "start":2,
                        "length":2,
                        "type":"bin"
                        },
                    "jis_reading":{
                        "start":4,
                        "length":4,
                        "type":"str"
                        },
                    "img":{
                        "start":8,
                        "length":504,
                        "dim":(64,63),
                        "type":"int",
                        "bitperpixel":1,
                        "n_pixels": 4032
                        }
                    },
                "9G":{
                    "sheet":{
                        "start":0,
                        "length":2,
                        "type":"int"
                        },
                    "kanji_code":{
                        "start":2,
                        "length":2,
                        "type":"bin"
                        },
                    "reading":{
                        "start":4,
                        "length":8,
                        "type":"str"
                        },
                    "data_number":{
                        "start":12,
                        "length":4,
                        "type":"int"
                        },
                    "eval_img":{
                        "start":16,
                        "length":1,
                        "type":"int"
                        },
                    "eval_group":{
                        "start":17,
                        "length":1,
                        "type":"int"
                        },
                    "gender":{
                        "start":18,
                        "length":1,
                        "type":"int"
                        },
                    "age":{
                        "start":19,
                        "length":1,
                        "type":"int"
                        },
                    "ind":{
                        "start":20,
                        "length":2,
                        "type":"int"
                        },
                    "occ":{
                        "start":22,
                        "length":2,
                        "type":"int"
                        },
                    "sheet_date":{
                        "start":24,
                        "length":2,
                        "type":"int"
                        },
                    "scan_date":{
                        "start":26,
                        "length":2,
                        "type":"int"
                        },
                    "sample_y":{
                        "start":28,
                        "length":1,
                        "type":"int"
                        },
                    "sample_x":{
                        "start":29,
                        "length":1,
                        "type":"int"
                        },
                    "img":{
                        "start":60,
                        "length":8128,
                        "dim":(128,127),
                        "type":"int",
                        "bitperpixel":4,
                        "n_pixels": 16256
                        }
                    },
                }


# T56Code, adapted from
# http://etlcdb.db.aist.go.jp/etlcdb/etln/t56code.htm
T56CODE = {0b000000:"0",
            0b100000:"^",
            0b000001:"1",
            0b100001:"J",
            0b000010:"2",
            0b100010:"K",
            0b000011:"3",
            0b100011:"L",
            0b000100:"4",
            0b100100:"M",
            0b000101:"5",
            0b100101:"N",
            0b000110:"6",
            0b100110:"O",
            0b000111:"7",
            0b100111:"P",
            0b001000:"8",
            0b101000:"Q",
            0b001001:"9",
            0b101001:"R",
            0b001010:"[",
            0b101010:"-",
            0b001011:"#",
            0b101011:"$",
            0b001100:"@",
            0b101100:"*",
            0b001101:":",
            0b101101:")",
            0b001110:">",
            0b101110:";",
            0b001111:"?",
            0b101111:"'",
            0b010000:" ",
            0b110000:"+",
            0b010001:"A",
            0b110001:"/",
            0b010010:"B",
            0b110010:"S",
            0b010011:"C",
            0b110011:"T",
            0b010100:"D",
            0b110100:"U",
            0b010101:"E",
            0b110101:"V",
            0b010110:"F",
            0b110110:"W",
            0b010111:"G",
            0b110111:"X",
            0b011000:"H",
            0b111000:"Y",
            0b011001:"I",
            0b111001:"Z",
            0b011010:"&",
            0b111010:"<-",
            0b011011:".",
            0b111011:",",
            0b011100:"]",
            0b111100:"%",
            0b011101:"(",
            0b111101:"=",
            0b011110:"<",
            0b111110:'"',
            0b011111:"\\",
            0b111111:"!"
            }

# Masks for decoding images.
# keys: number of bits per pixel
# values: dictionary of masks with pixel:mask/bitshift
pixel_masks = {
            4:{ # For 8 bit (1 byte) reads
                0:{
                    "mask":0b11110000,
                    "bitshift":4
                    },
                1:{
                    "mask":0b00001111,
                    "bitshift":0
                    }
            },
            6:{ # For 24bit (3 byte) reads
                0:{
                    "mask":0b111111000000000000000000,
                    "bitshift":18
                    },
                1:{
                    "mask":0b000000111111000000000000,
                    "bitshift":12
                    },
                2:{
                    "mask":0b000000000000111111000000,
                    "bitshift":6
                    },
                3:{
                    "mask":0b000000000000000000111111,
                    "bitshift":0
                    }
            },
            1:{ # For 8 bit (1 byte) reads
                0:{
                    "mask":0b10000000,
                    "bitshift":7
                    },
                1:{
                    "mask":0b01000000,
                    "bitshift":6
                    },
                2:{
                    "mask":0b00100000,
                    "bitshift":5
                    },
                3:{
                    "mask":0b00010000,
                    "bitshift":4
                    },
                4:{
                    "mask":0b00001000,
                    "bitshift":3
                    },
                5:{
                    "mask":0b00000100,
                    "bitshift":3
                    },
                6:{
                    "mask":0b00000010,
                    "bitshift":1
                    },
                7:{
                    "mask":0b00000001,
                    "bitshift":0
                    }
            }
        }
# A dictionary that stores num of bytes need to read to decode an image
bytes_to_read = {1:1, 4:1, 6:3}

# Factors for conversion to 8 bit grayscale
conversion_factor = {1:255, 4:17, 6:4}
